version: 1.0.0-{branch}-{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017 
init:
  - dotnet --version
build_script:
  - cmd: call cmd /C "cd .\build & build.cmd"  
test_script:
  - cmd: call cmd /C "cd .\build & test.cmd"
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: oy2kjwnyla5b57scwcjq7tzv72wuveoe3nebe6tzh2dz7q
  skip_symbols: true
  artifact: /.*\.nupkg/
  tag: $(APPVEYOR_REPO_TAG_NAME)
  on:
      branch: develop                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only