version: 1.0.0-{branch}-{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017 
init:
  - dotnet --version
build_script:
  - cmd: call cmd /C "cd .\build & build.cmd"  
test_script:
  - cmd: call cmd /C "cd .\build & test.cmd"
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: Mnscknp3/CsSxNMeZ71X8g0pyohmssUwLqvbKFo0AM1IgiFjNVvDCfNd3NTx4dR+
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only